apiVersion: v1
kind: Service
metadata:
  name: random-app
spec:
  type: NodePort
  selector:
    app: random-app
  ports:
    - port: 8080
      protocol: TCP
      targetPort: random-web-svc
      nodePort: 30007
